# Generated by Django 5.1 on 2024-08-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memebers',
            new_name='Members',
        ),
    ]
