# Generated by Django 5.1 on 2024-08-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_memebers_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
