# Generated by Django 5.1 on 2024-08-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_members_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
