# Generated by Django 5.1.2 on 2024-11-03 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('2d-1vs1', '2D 1v1'), ('2d-tournament', '2D Tournament'), ('3d-1vs1', '3D 1v1'), ('3d-tournament', '3D Tournament')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(to='pong.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='pong.player')),
            ],
        ),
    ]
